version: 2.1
orbs:
  azure-acr: circleci/azure-acr@0.2.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - azure-acr/build-and-push-image:
          login-server-name: ${LOGINSERVERNAME}
          registry-name: ${REGISTRYNAME}
          repo: dashboard
          tag: latest
          
