version: 2.1
orbs:
  azure-acr: circleci/azure-acr@0.2.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - azure-acr/build-and-push-image:
          login-server-name: coronasaferegistryup.azurecr.io
          registry-name: coronasaferegistryup
          repo: dashboard
          tag: latest